### ISSUE TITLE
Shared library size and ARM32 support

### ISSUE THREAD

**Issue by estutzenberger** [extism/extism#113]
Is there a shared library? If so, how large is it? We recently had a go with wasmedge (which is more like a vm), but the shared library is quite large (40 MB).

Does Extism have support or plan to have support for ARM32 host systems?

**Comment by zshipko** [comment]
Yes, there’s a shared library that’s around 10-20MB depending on your platform.

Right now I think the biggest thing holding back targeting arm is the fact that cranelift doesn’t have an arm backend. However, we’ve been discussing possibility of supporting a lighter-weight runtime in the future which would reduce the library size and potentially provide arm support.

**Comment by estutzenberger** [comment]
Ok, great. Thanks for the information! I'll keep an eye out for the mentioned changes.

**Comment by nilslice** [comment]
@estutzenberger - if you're still interested, we just released https://github.com/extism/extism-wamr which may support your target. It's built upon [WAMR](https://github.com/bytecodealliance/wasm-micro-runtime) and supports the following: 

https://github.com/bytecodealliance/wasm-micro-runtime?tab=readme-ov-file#supported-architectures-and-platforms
