### ISSUE TITLE
building for macOS-x86_64 but attempting to link with file built for macOS-arm64 GoLang 1.19.3 version

### ISSUE THREAD

**Issue by ananthdurai** [extism/extism#120]
I'm trying to execute the sample Go code from Extism from https://extism.org/docs/integrate-into-your-codebase/go-host-sdk. After the error, I tried to debug the problem, so I ran this pretty minimal code.

```
import (
	"github.com/extism/extism"
)

func callWasm() {
	ctx := extism.NewContext()
	defer ctx.Free() // this will free the context and all associated plugins
}
```
I'm getting the following error.

**GoLang Version:** 1.19.3

**Mac Chip:** Apple M1 Pro

```
# github.com/extism/extism
ld: warning: ignoring file /usr/local/lib/libextism.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_extism_context_free", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_context_free in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_context_free)
  "_extism_context_new", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_context_new in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_context_new)
  "_extism_context_reset", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_context_reset in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_context_reset)
  "_extism_error", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_error in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_error)
  "_extism_log_file", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_log_file in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_log_file)
  "_extism_plugin_call", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_plugin_call in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_plugin_call)
  "_extism_plugin_config", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_plugin_config in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_plugin_config)
  "_extism_plugin_free", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_plugin_free in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_plugin_free)
  "_extism_plugin_function_exists", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_plugin_function_exists in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_plugin_function_exists)
  "_extism_plugin_new", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_plugin_new in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_plugin_new)
  "_extism_plugin_output_data", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_plugin_output_data in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_plugin_output_data)
  "_extism_plugin_output_length", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_plugin_output_length in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_plugin_output_length)
  "_extism_plugin_update", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_plugin_update in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_plugin_update)
  "_extism_version", referenced from:
      __cgo_48636a3be7c2_Cfunc_extism_version in _x002.o
     (maybe you meant: __cgo_48636a3be7c2_Cfunc_extism_version)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Note:**
I'm able to run the sample wasm file with the Extism command line tool in my machine, only the GoLang code is not working

**Comment by bhelx** [comment]
Could you check the type of the dylibfile? it should be arm64. Run this command:

```
> file /usr/local/lib/libextism.dylib
/usr/local/lib/libextism.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

It looks to me like your go program is for some reason trying to compile to x86, but let's make sure the dylib is right.


> building for macOS-x86_64

Is the supcicous part to me

**Comment by bhelx** [comment]
Also please make sure you go is an arm64 version:

```
> go version
go version go1.19.2 darwin/arm64
```

**Comment by nilslice** [comment]
Ya I think you may be running a Go toolchain that was built for x86, but extism installed the native arm64 release since you're on a M1.

This line in your error caught my eye:

`ld: symbol(s) not found for architecture x86_64`

Did you install Go via brew?

**Comment by bhelx** [comment]
That's my suspicion too. If that's the case you will want to uninstall go (instructions depend on how you installed it) then install it again but explicitly use the arm version. I think the easiest way to do that is to get the pkg from: https://go.dev/dl/
The one labeled `Apple macOS (ARM64)`

**Comment by ananthdurai** [comment]
I tried to uninstall Go and install it back, 

`>go version                                                                                                                              ✘ 2
go version go1.19.3 darwin/amd64`

```
>file /usr/local/lib/libextism.dylib
/usr/local/lib/libextism.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

Both seem arm64, trying to debug further to see if I can find any insights.

**Comment by ananthdurai** [comment]
From the error, 

`ignoring file /usr/local/lib/libextism.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
`
GoLang Extism C lib compiled for `macOS-x86_64`, but the machine has the `macOS-arm64`. I suppose some issue with Extism Go dependency. Perhaps it requires compilation for M1 as a target?

**Comment by nilslice** [comment]
`extism install latest` should have downloaded an arm64 build based on detecting your system. But, you could download a release directly for your architecture and replace these files:

`/usr/local/lib/libextism.dylib`
`/usr/local/include/extism.h`

Release url: https://github.com/extism/extism/releases/download/v0.1.0/libextism-aarch64-apple-darwin-v0.1.0.tar.gz

**Comment by bhelx** [comment]
@nilslice i don't think that's it. His dylib file is correct. He's on an M1 and it's an arm binary. His Go install is still x86

> go version ✘ 2 go version go1.19.3 darwin/amd64
> Both seem arm64, trying to debug further to see if I can find any insights.

@ananthdurai `darwin/amd64` is x86 not arm

How are you installing Go? if you are using homebrew it might be installing the x86 version. I suggest uninstalling Go and installing via the instructions I listed above. Directly from the pkg from go.

**Comment by bhelx** [comment]
> GoLang Extism C lib compiled for macOS-x86_64, but the machine has the macOS-arm64. I suppose some issue with Extism Go dependency. Perhaps it requires compilation for M1 as a target?

@ananthdurai I believe the reason is that you have x86 version of go. Your M1 can run both binaries so it's not a problem until it needs to compile something. But now that it needs `cgo` it's expecting it to be x86 code. It's not the extism dependency i don't think.

**Comment by nilslice** [comment]
Good catch!

@ananthdurai - you may also be able to install via brew and get the native arm64 build of Go using:

`arch -arm64 brew install go`

**Comment by nilslice** [comment]
Hi @ananthdurai - just wanted to check in and see if you were able to get this resolved?

**Comment by ananthdurai** [comment]
@nilslice yes, that is the issue. I installed the ARM64 version of Go, and everything is working fine now. Thank you.

**Comment by nilslice** [comment]
Excellent, glad to hear that! Going to close the issue now, but please feel free to reopen if the issue reemerges.
