### ISSUE TITLE
Zig SDK?

### ISSUE THREAD

**Issue by jedisct1** [extism/extism#126]
Congrats for Extism, which looks like a really useful project.

However, especially given the number of supported languages, and its maturity regarding WebAssembly support, I was surprised to see Zig missing from the list.

Is a Zig SDK planned soon?

**Comment by nilslice** [comment]
We definitely want to support Zig - no one on the team currently has much Zig experience though so we've kind of put it off to prioritize languages we're more comfortable with. 

I recognize you from some Zig + wasm projects, thanks for checking out Extism! If you have some tips for us to do the Zig SDK + PDK, we'd be grateful. Even better if you wanted to help out with their implementations 🤘

**Comment by nilslice** [comment]
@jedisct1 - just an update here: @usdogu has very kindly contributed a PDK (https://github.com/extism/zig-pdk) in Zig, enabling Extism plug-ins to be written in Zig and compiled to wasm!

They are also working on an SDK now in #186. Please feel free to review or follow along. I am learning Zig, but still a ways off from feeling confident, so all input is helpful and welcome.

**Comment by jedisct1** [comment]
This is exciting news!

Yep, I'm definitely going to give the PDK a spin and take a look at the SDK as well.

Thanks for the great news!
