### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by millette** [extism/extism#129]
Add support for <https://deno.land/>, nodejs successor.

**Comment by nilslice** [comment]
This is definitely something we want to do. I was planning on starting it tonight actually. 

Do you think the API should be mostly the same as the Node.js one? I'm not so familiar with Deno but think there are maybe some other types/patterns that could be  used.

**Comment by lukevp** [comment]
I think the most maintainable way forward would be to have a single Typescript interface implementation that is used by node/deno/bun and wrap the FFI-specific code behind that implementation per host runtime. I haven't done any FFI based implementation though so I'm not sure what this would look like.

**Comment by nilslice** [comment]
It's also worth considering the possibility of re-using the Extism [`browser-runtime`](https://github.com/extism/extism/tree/main/browser/src), which is an implementation of the rust runtime on top of JavaScript-native WebAssembly APIs. If each of Bun/Deno/Node use the same APIs for WebAssembly, it might be advantageous to instead work on converging the browser runtime to this "universal" JavaScript SDK.

**Comment by bhelx** [comment]
For anyone landing on this issue, I was able to get it to work pretty easily by just using the browser runtime as @nilslice mentioned. All you need to do is import it like a normal npm package:

```js
import { ExtismContext } from "npm:@extism/runtime-browser@0.3.0"
```

See some more docs here: https://extism.org/docs/integrate-into-your-codebase/browser-runtime-sdk

I'm going to close this in favor of more focused discussions to come later. Perhaps there is more we can do to better integrate with Deno.
