### ISSUE TITLE
use double;

### ISSUE THREAD

**Issue by shijunti19** [extism/extism#142]
PHP 8.1.13 (cli) (built: Dec  6 2022 16:56:17) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies

Package operations: 4 installs, 0 updates, 0 removals
  - Installing ircmaxell/php-object-symbolresolver (dev-master dfe1b1a): Extracting archive
  - Installing ircmaxell/php-c-parser (dev-master fd8f5ef): Extracting archive
  - Installing ircmaxell/ffime (dev-master f6911d7): Extracting archive
  - Installing extism/extism (v0.1.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception

In ExtismLib.php line 1:
                                                                   
  **The use statement with non-compound name 'double' has no effect**  
                                                                   
```
<?php use double;//《=why
interface iExtismLib {}
interface iExtismLib_ptr {}
```
composer require extism/extism

why?

**Comment by nilslice** [comment]
@shijunti19 - this has been fixed, and we will release a new version of the SDK soon with the updated library dependency.

**Comment by nilslice** [comment]
@shijunti19, actually, since we use the `dev-master` branch in the dep, all you need to do is run:
`composer update` and the latest library version will be used. I tested this locally and the fix was applied. Please let us know if yours is not fixed by this update.
