### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shijunti19** [extism/extism#145]
![image](https://user-images.githubusercontent.com/5392211/206056784-896ef930-1e67-4a35-92de-2c6a23a34c90.png)

composer remove extism/extism

![image](https://user-images.githubusercontent.com/5392211/206056957-e88d6719-6189-48cc-b209-4a7bb8031453.png)
Your latest version has been corrected. These outputs should not appear

**Comment by nilslice** [comment]
Hi @shijunti19 -

Sorry, I do not understand. 

Are you still experiencing a problem with the PHP SDK? My tests showed that the problem was fixed, but you are still seeing something wrong?

**Comment by shijunti19** [comment]
@shijunti19 In the morning, after I installed your latest version, all the output will take extra characters

![Uploading image.png…]()
There should be no such characters

**Comment by shijunti19** [comment]
![image](https://user-images.githubusercontent.com/5392211/206197215-2667ff8f-26cd-421e-b8fd-1941dad35552.png)

**Comment by nilslice** [comment]
I see - thank you. The latest version fixes this issue. Make sure to run `composer update` - you may have the old version listed in your lock file.

**Comment by shijunti19** [comment]
@nilslice 
I cannot update to without upgrading the version number

Unable to update to repair

**Comment by shijunti19** [comment]
https://github.com/phper-framework/phper
Personally, it is much faster to use rust to write components to load plug-ins than PHP

**Comment by nilslice** [comment]
Can you try starting a new project in a new directory? Then:

`composer require extism/extism`

and run the new project?

Im fairly certain the bug is fixed, but there may be something in your project that has the old code cached somewhere.
