### ISSUE TITLE
Configurable HTTP timeouts

### ISSUE THREAD

**Issue by nilslice** [extism/extism#151]
For `extism_http_request` in particular, we should add both host-configurable HTTP timeouts for call-outs made from a plug-in, as well as a way to set it from the PDK, but not to exceed one if set by the host. The PDK should only be able to set a timeout that is shorter than one set by the host.

**Comment by bhelx** [comment]
Seems like we went with the global timeout and maybe we should put this on ice for now. Feel free to open again if you disagree @nilslice
