### ISSUE TITLE
WASI support in the browser runtime

### ISSUE THREAD

**Issue by bhelx** [extism/extism#160]
We currently don't support WASI

Screenshot from the playground:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/185919/207105539-c2535f02-806b-4237-9faf-88ca433bc70c.png">

Putting this issue here to track the problem.

**Comment by nilslice** [comment]
Some options to consider: 
- https://github.com/cloudflare/workers-wasi
- https://docs.wasmer.io/integrations/js/wasi/browser
- https://github.com/taybenlor/runno/blob/main/packages/wasi-motor/lib/wasi/wasi.ts
- any others?

**Comment by sunfishcode** [comment]
Another option is: 
 - https://github.com/bjorn3/browser_wasi_shim 

It doesn't have everything, but it is a small and simple codebase that'd be easy to extend.

**Comment by bhelx** [comment]
Thanks @sunfishcode that seems to meet our requirements!
