### ISSUE TITLE
Is there a way to ignore unexpected "__wbindgen_*" functions?

### ISSUE THREAD

**Issue by piaoger** [extism/extism#184]
While trying to build one larger module with extism, I got below message while loading the wasm file in playground.

It seems that there are some wasm-bindgen related artifacts in the wasm file. Maybe it's caused by rand/getrandom crate but I have not look into this issue. On the other hand, I can load the resutant wasm file with same funtionality generated by wasm-pack instead. 

- error message

```text
TypeError: import object field '__wbindgen_placeholder__' is not an Object
```
- screenshot

![image](https://user-images.githubusercontent.com/179429/209467647-2b37f962-e91f-4237-9579-d275776b2f59.png)

![image](https://user-images.githubusercontent.com/179429/209467789-5fd59315-2694-483f-b95c-9a75715a33f8.png)

**Comment by nilslice** [comment]
@piaoger - unfortunately, this is a side-effect of compiling some rust crates to `wasm32-unknown-unknown`, which sometime assume you're targeting a web browser environment. 

It could be the rand/getrandom crates, or it could be something else. I would try to remove the `features = ["js"]` if you have it enabled in your `Cargo.toml` for `getrandom`. I'm not sure that this will still compile for `wasm32-unknown-unknown` though, so if you need random values, you probably need to compile for `wasm32-wasi`. If you do WASI, you won't be able to run it in the playground, so it's not really a solution here. We are working on adding partial WASI support to the Extism browser runtime though, which should help solve these issues. 

By the way, if you're doing introspection on your WASM modules to try and debug issues, we have a free browser app that might be helpful: https://modsurfer.app

**Comment by nilslice** [comment]
Cross-linking browser-runtime / playground WASI support tracking issue: https://github.com/extism/extism/issues/160

**Comment by nilslice** [comment]
@piaoger - yes, it's great to have more support for WASI in the browser runtime! Thanks to @bhelx for adding that 🤘

What are you looking to do with the JS environment? It may be a little out of scope for this plug-in system, but maybe there is a way we can help you integrate.

**Comment by bhelx** [comment]
I don't think this is an issue we can specifically solve at the moment. Though perhaps someone wants to try to tackle it. Maybe one idea would be to offer up some kind of linked module that satisfies known wbingen imports?

@piaoger in the meantime, if you're willing to implement the imports yourself as you've demonstrated, i think our new JS-SDK should help you. You can implement imports with it: https://github.com/extism/js-sdk
