### ISSUE TITLE
Installation Issue on MacOS Monterey - M1 Mac Pro

### ISSUE THREAD

**Issue by lukevp** [extism/extism#189]
I ran into an issue installing extism CLI on an M1 Pro Macbook with Monterey with the `extism install latest` command.  I had to `sudo extism install latest` for the /usr/local/lib/include path to be created correctly.  

Without Sudo:
```
➜  extism install latest
Getting release for latest
Installing to /usr/local (version v0.1.0)
Password:
Installed /usr/local/lib/libextism.dylib
cp: /usr/local/include/extism.h: No such file or directory
Installed /usr/local/include/extism.h

➜  cat /usr/local/include/extism.h
cat: /usr/local/include/extism.h: No such file or directory

➜  extism version
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/extism_cli/__init__.py", line 472, in import_extism
    import extism
[... snip stacktrace ...]
extism.extism.Error: Unable to locate the extism library and header file
```

With Sudo:
```
➜  sudo extism install latest
Getting release for latest
Installing to /usr/local (version v0.1.0)
Installed /usr/local/lib/libextism.dylib
Installed /usr/local/include/extism.h

➜  extism version            
0.1.0
```

Looks like my user doesn't have rights to create the /usr/local/include/ path or something's wrong with the first time run of the script, something like that.

**Comment by bhelx** [comment]
Maybe this needs to change to require sudo: https://github.com/extism/cli/blob/987f0fdbcfe103a578fc57c385bf831c8733ecc4/extism_cli/__init__.py#L349

**Comment by bhelx** [comment]
Looks like it is asking for your password though. So that's confusing

**Comment by bhelx** [comment]
I cannot seem to repro. Trying a new bash session too:

```
[I] ben@m1lap ~ [1]> rm /usr/local/include/extism.h
override rwxr-xr-x root/wheel for /usr/local/include/extism.h? 
[I] ben@m1lap ~> extism install latest
Getting release for latest
Installing to /usr/local/ (version v0.1.0)
Password:
Installed /usr/local/lib/libextism.dylib
Installed /usr/local/include/extism.h
```

**Comment by lukevp** [comment]
I believe the issue is because I did not have a `/usr/local/include` folder, and the /usr/local dir is only writable by root on my Mac.  If you look at the `cp` definition itself, it will auto-sudo if the path is in /usr/.  However, [the native mkdir command](        https://github.com/extism/cli/blob/987f0fdbcfe103a578fc57c385bf831c8733ecc4/extism_cli/__init__.py#LL339C17-L339C17) is being used to create the directory,  so even though the command does a sudo later for writing the file and that works correctly, the script fails if you do not yet have `/usr/local/include`.  I think mkdir needs to be wrapped in an auto-sudo like the cp function.

Here are the permissions for my `/usr/local` showing it's only writable by root
```
➜  local ls -al /usr/local
total 0
drwxr-xr-x   6 root  wheel  192 Dec 29 17:09 .
drwxr-xr-x@ 11 root  wheel  352 Aug 24 01:59 ..
drwxr-xr-x  14 root  wheel  448 Dec 22 21:58 bin
drwxr-xr-x   3 root  wheel   96 Dec 29 17:09 include
drwxr-xr-x   4 root  wheel  128 Dec 29 17:08 lib
drwxr-xr-x   3 root  wheel   96 Dec 19 19:14 share
```

Here's the listing of my include dir showing extism is the only thing in there.  you may have already had this directory created so didn't run into this issue, since the cp command is correctly sudoing. The only issue seems to be in the mkdir part.
```
➜  local ls -al /usr/local/include
total 8
drwxr-xr-x  3 root  wheel    96 Dec 29 17:09 .
drwxr-xr-x  6 root  wheel   192 Dec 29 17:09 ..
-rw-r--r--  1 root  wheel  3042 Dec 29 17:09 extism.h
```

**Comment by zshipko** [comment]
Closing this because the new CLI has been released
