### ISSUE TITLE
Rich `Context` API and decoupling `Plugin`s

### ISSUE THREAD

**Issue by ok-nick** [extism/extism#202]
[extism::Context](https://docs.rs/extism/latest/extism/struct.Context.html) has two, very minimal functions for managing a pool of plugins. Underneath the hood, in [extism_runtime::Context](https://docs.rs/extism-runtime/latest/extism_runtime/struct.Context.html), there are numerous useful functions that could be exposed so that the user doesn't need to reimplement it themselves.

I found that I often need to manage a pool of `Plugin`s. To currently do this, you must create your own collection, when `extism_runtime::Context` already does this for you. 

On that note, I think it might be a little nicer to decouple a `Plugin` and a `Context`. You can create a plugin on your own, then when you want to use it, you upload it to a `Context`. I think the reason this wasn't done originally is so that you don't have to pass a `Context` to `Plugin::call`, which is why I also think that  there should be a distinction between a `Plugin` and a `PluginSchema`. Essentially, a `PluginSchema` is a way to upload a WASM module to a `Context` with a given `Manifest` and other additional information. After upload, it will return a reference to the `Plugin` to which you can then call functions on. When you need it for another time, you pull the `Plugin` from the `Context`, using the proper API, then operate on it. This turns a `Context` into a custom collection for managing `Plugin`s.

In addition to the above, it would also be useful to expose `PluginIndex`s and possibly `extism_runtime::Context::next_id`. I found that I want to generate ids for plugins to identify them, however, these plugins are not directly managed by `extism`. Maybe the "unique id" system should be decoupled into a separate struct that is used by a `Context` and could be passed by the user (otherwise defaulted).

Edit: I see the point of why `Context`s aren't a proper collection is because a `Plugin` can be freed after being dropped. That's nice and all, but often times I need to store it and call it later. Why force the user to create their own collection when it's done internally? `extism` can still expose a wrapper struct around a `Plugin` that frees on drop, but I just don't think it's that useful when users can free them by calling a separate function.

**Comment by zshipko** [comment]
Thanks for the suggestions! I think some of these ideas could be nice - a way to move a plugin across contexts could be interesting but it's not really on our roadmap right now - I would be happy to review a PR!

Without that capability a plugin's lifetime depends on the lifetime of the context used to create it - you can manually ensure that the context lives long enough and use `std::mem::forget(plugin)` then `drop(plugin)` but I'm not convinced that should be the default behavior.

**Comment by ok-nick** [comment]
Yes, my point was that the `Context` owns the `Plugin`s. The only way for a user to access a `Plugin` is to get a reference from the `Context`. Therefor, when a `Context` is dropped, so do all the plugins. However, if you want to free a specific plugin you can do so using the dedicated `free_plugin` function from the `Context`.

**Comment by ok-nick** [comment]
I took a look at the `main` branch and it looks like `PluginBuilder` takes the place of my idea for `PluginSchema`, I like the builder better. Otherwise, for the `Plugin`, the `drop` function should be removed and a new function named `free_plugin` should be added to the `Context`. As I said before, sometimes you need to store a plugin and call it later, you don't want it to free itself after you call one function.

I'd be happy to implement a PR for some of these things and you could take a look?

**Comment by zshipko** [comment]
Yeah, I would be happy to take a look, but I'm not sure removing drop by default is the right way to go.

I can think of a few other options: adding a new type `PersistenPlugin(Plugin)` with an explicit `free` function where the inner value is `std::mem::forget` or a function like `Plugin::into_id` that returns the ID after calling `std::mem::forget` - there are lots of ways to achieve the same thing. 

Our Elixir bindings use `std::mem::forget` on plugins, that might be a good place to experiment with some of these ideas: https://github.com/extism/extism/blob/main/elixir/native/extism_nif/src/lib.rs
