### ISSUE TITLE
[Node Host SDK | Host function] the value returned by a host function is truncated if I use emojis

### ISSUE THREAD

**Issue by k33g** [extism/extism#229]
👋 Hello,
I'm using the Node Host SDK  and the Go PDK.

On the Node.js side, this is the code of the host function:
```javascript
function hey_peeps(currentPlugin, inputs, outputs, userData, userData1) {
  console.log("🤗 Hello from Javascript 💜")

  // Read the function parameter from the memory
  let mem = currentPlugin.memory(inputs[0].v.i64)
  // Display the string argument passed to the host function
  console.log("🤖", mem.toString()) 
  
  // Print user data
  console.log("🖐️", userData)
  console.log("🖖", userData1)
  
  // Return a value
  const helloMessage = `👋 Hello ${mem.toString()} 🌍`
  var offs = currentPlugin.memoryAlloc(helloMessage.length)
  currentPlugin.memory(offs).write(helloMessage)
  outputs[0].v.i64 = offs;
}
```

On the TinyGo side, this is the code of the plugin:
```golang
package main

import (
	"github.com/extism/go-pdk"
)

//export hey_peeps
func hey_peeps(x uint64) uint64

//export heyPeople
func heyPeople() int32 {
	// Read the function parameter
	name := pdk.Input()

	// Call the host function whith the name as parameter
	// 1. copy the parameter to the memory
	mem_param := pdk.AllocateString(string(name))
	// 2. call the host function
	offs := hey_peeps(mem_param.Offset())

	// 3. read the return data
	mem_param = pdk.FindMemory(offs)

	// 4. copy the content of the memory to a buffer
	b := make([]byte, mem_param.Length())
	mem_param.Load(b)

	// 5. prepare the JSON value to return
	output := `{"message": "👋 Hello World 🌍 from Go","input": "` +
		string(name) +
		`","result":"` + string(b) + `"}`

	// Allocate space into the memory
	mem := pdk.AllocateString(output)
	// zero-copy output to host
	pdk.OutputMemory(mem)

	return 0
}

func main() {}
```

The result of the call of the plugin is: 
```json
{"message":"👋 Hello World 🌍 from Go","input":"Jane Doe","result":"👋 Hello Jane Doe "}
```

The expected result should be:
```json
{"message":"👋 Hello World 🌍 from Go","input":"Jane Doe","result":"👋 Hello Jane Doe 🌍"}
```

**Comment by bhelx** [comment]
I think this is the problem:

```
> let str = "hello 🌎"
undefined
> str.length
8
> Buffer.byteLength(str)
10
```

`String#length` in javascript counts the characters and not the bytes.

I think you need to change this:

```js
  var offs = currentPlugin.memoryAlloc(helloMessage.length)
```

to this:

```js
  var offs = currentPlugin.memoryAlloc(Buffer.byteLength(helloMessage))
```

Could you try that?

Did you get this from an example? We probably should change this in other places or start thinking about some abstractions that can help prevent these kinds of footguns.

**Comment by k33g** [comment]
`Buffer.byteLength(helloMessage)` does the job 👍  thank you 🙇 

My sample is a mix between the doc and a chat in the Discord https://discord.com/channels/1011124058408112148/1050088035691270204/1066403189211017257

I think we can close the issue

**Comment by syke99** [comment]
I agree with @bhelx Emojis are stored in Unicode code points, and some are comprised of multiple Unicode points. So when working with emojis in strings and setting byte arrays to the length of said string, the only safe way to do so with `Buffer.byteLength()`

**Comment by bhelx** [comment]
Right, I think we should always use byteLength regardless of what encoding we think the string is because it works for all encodings. This is an easy mistake to make though, and we made it when writing this library: https://github.com/extism/extism/pull/82

Next steps would be to agree on a slightly higher level API for host functions to help prevent these kind of footguns. Perhaps we could have a method kind of like this:

```typescript
class Plugin {
  allocBytes(data: Uint8Array | String): number {
      let offs = this.memoryAlloc(Buffer.byteLength(data))
      this.memory(offs).write(data)
      return offs
  }
}
```

We'd like to take some time and come up with something consistent for all the SDKs though, so for now best to just try to document this better.
