### ISSUE TITLE
use typescript for node sdk

### ISSUE THREAD

**Issue by nilslice** [extism/extism#25]
While it adds a compile step to testing and release, I think having a typed API for node will be an improvement.

**Comment by bhelx** [comment]
I agree I prefer a typescript port and it should be easy, but a quicker fix might be to ship with "declaration file" (`.d.ts`extension).

**Comment by nilslice** [comment]
Yea that sounds like a great place to start!

**Comment by bhelx** [comment]
Closed by #43
