### ISSUE TITLE
Support wasmtime "fuel" limits

### ISSUE THREAD

**Issue by bhelx** [extism/extism#26]
The Wasmtime runtime has a concept of "fuel" which meters the consumption of WASM instructions. This would allow the host to limit a plugin's execution. The host could have some defaults and maybe dymanically change the amount of fuel given to a plugin depending on their customer's needs.

https://docs.wasmtime.dev/api/wasmtime/struct.Store.html#method.add_fuel

This is probably not hard to add but might have a broader discussion about how to expose this in the Host SDK API.

**Comment by nilslice** [comment]
I think with #163, we can close this out as it generally covers the same resource control/limit - but maybe "fuel" is something we look more closely at in specific later down the line.
