### ISSUE TITLE
Setup rubygems release / bundle configuration

### ISSUE THREAD

**Issue by nilslice** [extism/extism#28]
The Ruby SDK located in the `ruby` directory in the root of this repo contains a starting point for submitting the code as a gem. 

Join us on Discord to chat about this issue:

[![Discord](https://img.shields.io/discord/1011124058408112148?color=%23404eed&label=Community%20Chat&logo=Discord&logoColor=%23404eed)](https://discord.gg/cx3usBCWnc)

**Comment by bhelx** [comment]
Apologies I think I've done this one
