### ISSUE TITLE
Embedding runtime in a rust based compiler

### ISSUE THREAD

**Issue by bcpeinhardt** [extism/extism#312]
Hey there!
So I'm fond of a programming language called gleam. It's a functional language that compiles to erlang and javascript and the compiler is written in rust.
I'd like to explore an SDK for gleam, but not sure where to start. I think I'd like to try skipping the whole c ffi thing, and use the runtime crate directly from the gleam compiler (also written in rust). The idea would be basically language level support for loading extism plugins, honestly because it sounds easier than trying to create all the binding infrastructure over again in gleam.
So I'm creating this issue to ask basically what you think the viability is and get some hints on where to start with the runtime crate?

**Comment by nilslice** [comment]
Hi @bcpeinhardt -

That sounds like a cool idea! 

I'm curious if you could make use of the [Rust SDK](https://extism.org/docs/integrate-into-your-codebase/rust-host-sdk/) in the compiler instead, and maybe wrap it with Gleam APIs? Apologies, still no fully clear on the precise use cases you're going for. Happy to learn more if you could illustrate  how you'd want to use Extism!

**Comment by bcpeinhardt** [comment]
You're not clear because I'm not clear haha, just exploring right now. I'm not sure if I could, the gleam compiler targets erlang and javascript, so it may be the case that I need to produce generated code that utilizes the javascript and erlang sdks haha. 
The use case is to have an sdk for gleam. I was just thinking about whether I needed to do the whole c ffi thing or if I could leverage the fact that the compiler is rust. Here is the general structure of the compiler:
https://github.com/gleam-lang/gleam/tree/main/docs/compiler

**Comment by bhelx** [comment]
Right now, if your host runtime is using Rust in some way, you can skip the FFI part and statically embed the Extism runtime as a rust library. This is what the Rust SDK does. This is also, kind of, what the Elixir library does through it's Nif. This is a runtime concern though. I know the Gleam compiler is written in Rust but if it emits BEAM bytcode, it can't bring the Extism runtime along with it. This is my first-glance understanding, don't take my word as gospel.

So i guess the question is what do you want to target as a runtime? If you want to target the BEAM VM, maybe you can make use of the NIF we created for the Extism runtime.

If you want to target JS, maybe it depends on the platform, but you'll probably need to use FFI. You might want to see if there is any prior art to this. Like, some Gleam package that is utilizing a c or rust library. there may be more tooling out there for this than i am aware of.

**Comment by bhelx** [comment]
Having said all that, would love to help support this idea. A long time ago, I wrote down what I wanted in a perfect programming language and what popped out was nearly the the same as Gleam. It was a bit before I had the capability and motivation to build it myself though. Would love an excuse to dive into it.

**Comment by bhelx** [comment]
@bcpeinhardt did you have a chance to look into this idea?

**Comment by bcpeinhardt** [comment]
Hello!
No it's been busy at work, but I still very much plan to. I'll keep you updated and post a link to a repo here if I make any real progress.
In the meantime, if you haven't already I encourage you to join the gleam discord, it's very friendly and active :)

**Comment by bhelx** [comment]
I did a small amount of research. Reusing the nif may work. But would like to explore other options. If there is a gleam community or discord that might be a good place to start with a query
