### ISSUE TITLE
cURL installation method on Linux may fail

### ISSUE THREAD

**Issue by wikiwong** [extism/extism#339]
When installing extism on an ubuntu based distro using the cURL method: https://extism.org/docs/install#linux , it fails because:
```
mv: cannot move '/tmp/extism-cli' to '/home/{{your user}}/.local/bin/extism': No such file or directory
```

The solve was simply to create the bin directory at that location:
```
mkdir -p /home/{{your user}}/.local/bin
```

**Comment by bhelx** [comment]
Closed with https://github.com/extism/cli/pull/21
