### ISSUE TITLE
TypeError when using extism cli to call plugin function

### ISSUE THREAD

**Issue by mattjohnsonpint** [extism/extism#458]
Per https://extism.org/docs/install#call-plug-in-functions - I should be able to do this:

```sh
extism call --input "this is a test" test/code.wasm count_vowels
```

On the current 0.5.0 version, that fails with the following:

```
Traceback (most recent call last):
  File "/home/matt/.local/bin/extism", line 607, in <module>
    main()
  File "/home/matt/.local/bin/extism", line 598, in main
    plugin = libextism.Plugin(manifest, wasi=args.wasi, config=config)
  File "/home/matt/.local/lib/python3.10/site-packages/extism/extism.py", line 210, in __init__
    self.plugin = _lib.extism_plugin_new(
TypeError: initializer for ctype 'ExtismContext *' must be a cdata pointer, not bytes
```

If it matters, this is on Ubuntu 22.04 running in WSL.

I can call the same function just fine from the getting started sample apps, just not from the Extism CLI.

**Comment by nilslice** [comment]
Thanks, @mattjohnsonpint!

Please see this issue for a possible fix:

https://github.com/extism/cli/issues/24#issuecomment-1714454955

Also worth noting that we are close to shipping a new CLI that has no dependencies - so this will not be a problem in the future once that CLI is ready. 

Let me know if you'd like to try it out and we can get you access.

**Comment by nilslice** [comment]
(actually it's already in the `go-cli` branch here: https://github.com/extism/cli)

**Comment by mattjohnsonpint** [comment]
It's not critical - I just wanted to make sure y'all knew about it.  Thanks.

**Comment by zshipko** [comment]
The new CLI has been merged!
