### ISSUE TITLE
Testing: Resources/organization

### ISSUE THREAD

**Issue by bhelx** [extism/extism#487]
- Where do we store the test .wasm files how do we keep them versioned? Probably makes sense to keep them in one repo then use git submodules but we also discussed maybe building some infrastructure around this
- Ensure that the `extism-runtime.wasm` kernel is updated automatically, or semi-automatically (4 hours)
    - SDKs that require the kernel should get automatic PRs when this file changes

**Comment by bhelx** [comment]
I part 1 was taken care of with the [extism/plugins](https://github.com/extism/plugins) repo

@zshipko is part 2 take care of by the development build process?

**Comment by zshipko** [comment]
The only thing left is to update the go-sdk and js-sdk when the kernel changes. I think this could be considered complete and we can open some issues on those repos for more specific tasks.

**Comment by neuronicnobody** [comment]
Can continue manual approach for now while determining how to automate more fully

**Comment by chrisdickinson** [comment]
Noting that I'll take this on as a back-burner task. Goals are:

- Make sure the Go and JS SDKs continue to work against `extism-runtime.wasm` changes
- Keep the `extism-runtime.wasm` file vendored in the Go and JS SDKs up-to-date automatically. (Possibly by submitting PRs against those repos whenever the runtime artifact changes.)

**Comment by nilslice** [comment]
@chrisdickinson this may be a viable option... https://github.com/orgs/community/discussions/49745

Imagine running a step like this (opening a PR with the new kernel to `go-sdk` and `js-sdk`) from the `release` action in `extism/extism`

**Comment by bhelx** [comment]
Did we ever complete step 2? If not can we open a new issue to track it?

**Comment by zshipko** [comment]
The kernel isn't being updated automatically right now since it's only really the Go SDK that needs to get updates and we just haven't automated that yet - I guess now there is also the wamr-sdk, so it could be worth it if we keep adding support for more runtimes.
