### ISSUE TITLE
Provide users with a Github Action to use the Extism CLI

### ISSUE THREAD

**Issue by bhelx** [extism/extism#489]
Provide users with a Github Action to use the Extism CLI

**Comment by neuronicnobody** [comment]
Have something that works but should move to its own repo to improve the experience

**Comment by neuronicnobody** [comment]
@Ben check in on this

**Comment by bhelx** [comment]
We do have an action to install the CLI: https://github.com/extism/cli/tree/main/.github/actions/extism-cli
perhaps we should follow up and better document it?
