### ISSUE TITLE
error while executing at wasm backtrace:

### ISSUE THREAD

**Issue by w01fb0ss** [extism/extism#501]
manifest code:
![图片](https://github.com/extism/extism/assets/44709004/54235af3-6674-40f9-b2eb-20ef4ef1bc2e)
plugin code:
![图片](https://github.com/extism/extism/assets/44709004/d7efed4d-2060-4656-8c22-f9e343d9a730)
panic:
![图片](https://github.com/extism/extism/assets/44709004/672867e5-b58a-4155-ae32-3f7452a2a089)

**Comment by w01fb0ss** [comment]
Is there any sample code for accessing the file system?

**Comment by nilslice** [comment]
@w01fb0ss - this worked for me.. would you be able to try my reproduced version of your code and see if it fails similarly on your machine? 

https://github.com/nilslice/debug-501

**Comment by w01fb0ss** [comment]
> @w01fb0ss - this worked for me.. would you be able to try my reproduced version of your code and see if it fails similarly on your machine?
> 
> https://github.com/nilslice/debug-501

The code runs successfully, sorry, this is my problem, I will close this issue
