### ISSUE TITLE
Static linking extism with c and c++ sdks

### ISSUE THREAD

**Issue by G4Vi** [extism/extism#551]
It would be nice to have a way to build extism into c and c++ applications instead of needing to dynamically link it and sdks.

- [x] build libextism statically https://github.com/extism/extism/pull/552
- [x] update cli https://github.com/extism/cli/commit/4f055ba8dd2730a0d36b477ecba919cbacf0c0d0
- [x] build cpp-sdk statically

Edit: Added checklist

**Comment by zshipko** [comment]
This is a great idea! For C support I think the first step is to just generate the static library by adding `staticlib` to the libextism crate-type field. But updating https://github/extism/cpp-sdk will probably be a little more involved.
