### ISSUE TITLE
via proto conversation: add example of using extism+tracing to rust runtime

### ISSUE THREAD

**Issue by neuronicnobody** [extism/extism#586]
Add a test that uses the extism rust sdk alongside the tracing crate to run a plugin that intentionally errors, then verify that we can extract useful logging output from the failure (specifically, extism `log::error!` macro output.)

This might be best as a `example`, since `cargo test` runs these after unit tests.

**Comment by zshipko** [comment]
Extism uses tracing now, and tracing-subscriber supports `log` using a feature!
