### ISSUE TITLE
extism_length returns garbage values when an ExtismPointer is not aligned with an alloc

### ISSUE THREAD

**Issue by G4Vi** [extism/extism#634]
```c
uint8_t outputConfig[12];
memset(outputConfig, 'A', 12);
ExtismPointer ep = extism_alloc_string((const char *)outputConfig, sizeof(outputConfig));
static char message[256];
snprintf(message, sizeof(message), "the lengths %u %u %u %u\n", ((uint32_t)extism_length(ep)), ((uint32_t)extism_length(ep + 1)), ((uint32_t)extism_length(ep + 2)), ((uint32_t)extism_length(ep + 3)));
extism_log(message, strlen(message), ExtismLogError);
```
`2023-12-14T23:26:30.583608Z ERROR extism::pdk: the lengths 12 1090519040 1094778880 1094795520`

Looking at `fn length` in `kernel/src/lib.rs`  it looks like it's supposed to return 0 when a block isn't found.

**Comment by zshipko** [comment]
Thanks! This is a good catch, it looks like the current `extism_length` implementation assumed the offset passed in was a valid block - I have an update here: https://github.com/extism/extism/pull/635 to make sure the block is valid before checking the length.
