### ISSUE TITLE
[Question] nodejs call rust wasm function failed.

### ISSUE THREAD

**Issue by MDGSF** [extism/extism#639]
Hello, I am new to extism, I just copy the example, it seems some error happens, Is there anyone cognizant of the reasons behind this unfortunate occurrence?

This is rust code build success with `cargo build --target wasm32-unknown-unknown --release`
```
use extism_pdk::*;

#[plugin_fn]
pub fn greet(name: String) -> FnResult<String> {
    Ok(format!("Hello, {}!", name))
}

#[plugin_fn]
pub fn process_bytes(input: Vec<u8>) -> FnResult<Vec<u8>> {
    Ok(input)
}

#[derive(serde::Deserialize)]
struct Add {
    a: i32,
    b: i32,
}

#[derive(serde::Serialize)]
struct Sum {
    sum: i32,
}

#[plugin_fn]
pub fn add(Json(input): Json<Add>) -> FnResult<Json<Sum>> {
    let sum = Sum {
        sum: input.a + input.b,
    };
    Ok(Json(sum))
}
```

This is nodejs, when I run with `node index.js`, error happens.
```
const createPlugin = require("@extism/extism")

async function main() {
  const plugin = await createPlugin(
    '../math-extism-wasm/target/wasm32-unknown-unknown/release/math_extism_wasm.wasm',
    { useWasi: true }
  );

  {
    let res = await plugin.call("greet", "John");
    console.log(res.text())
  }

  {
    const input = JSON.stringify({
      a: 10,
      b: 20,
    });
    console.log(input);
    let res = await plugin.call("add", new TextEncoder().encode(input));
    console.log(res);
    let sum = JSON.parse(res.buffer);
    console.log(sum);
  }
}

main();
```

```
$ node index.js 
(node:18202) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18202) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Hello, John!
{"a":10,"b":20}
_PluginOutput [DataView] {
  byteLength: 10,
  byteOffset: 0,
  buffer: ArrayBuffer {
    [Uint8Contents]: <7b 22 73 75 6d 22 3a 33 30 7d>,
    byteLength: 10
  }
}
undefined:1
[object ArrayBuffer]
 ^

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at main (/home/huangjian/git/huangjian/RockStar/t005_js_plugins/plugins/mathcalc/backend/use-math-extism-wasm/index.js:22:20)

Node.js v18.18.2
```

**Comment by chrisdickinson** [comment]
Hi! Sorry for the trouble. It looks like you're calling `JSON.parse` on `res.buffer`; this will call `toString` on the `ArrayBuffer` before attempting to parse. That will result in the string `"[object ArrayBuffer]"`.

To fix this, you should be able to use one of the following:

- `res.json()` will encode the result buffer as a string and parse the result.
- `JSON.parse(res.text()) ` is equivalent to the above.
- `JSON.parse(new TextDecoder().decode(res))` treats `res` as a `DataView` over utf-8 bytes, decodes to a string, then parses the JSON.

Hopefully this helps -- I'll update the JS example this weekend. Thanks!

**Comment by MDGSF** [comment]
> Hi! Sorry for the trouble. It looks like you're calling `JSON.parse` on `res.buffer`; this will call `toString` on the `ArrayBuffer` before attempting to parse. That will result in the string `"[object ArrayBuffer]"`.
> 
> To fix this, you should be able to use one of the following:
> 
> * `res.json()` will encode the result buffer as a string and parse the result.
> * `JSON.parse(res.text()) ` is equivalent to the above.
> * `JSON.parse(new TextDecoder().decode(res))` treats `res` as a `DataView` over utf-8 bytes, decodes to a string, then parses the JSON.
> 
> Hopefully this helps -- I'll update the JS example this weekend. Thanks!

Thanks so much!! It works.
