### ISSUE TITLE
runtime: update `Plugin::function_extists` and `extism_plugin_function_exists` to check the type of the functions too

### ISSUE THREAD

**Issue by zshipko** [extism/extism#654]
`Plugin::function_extists` and `extism_plugin_function_exists`  should check the signature of the functions to ensure they can be called by the Extism runtime.

A function is valid only if it takes no parameters and returns either an `I32` or nothing.

**Comment by OLUWAMUYIWA** [comment]
First timer here. I'd like to pick this up.

**Comment by zshipko** [comment]
Awesome!

This would require updating [`function_exists`](https://github.com/extism/extism/blob/822cec40935f905b5adb9b400f1686a886d15220/runtime/src/plugin.rs#L403) to check the type of the params/results [here](https://github.com/extism/extism/blob/822cec40935f905b5adb9b400f1686a886d15220/runtime/src/plugin.rs#L406) instead of just checking `is_some`. Only functions that have no parameters and return either an `I32` or nothing should be considered valid.

Let me know if you have any questions!

**Comment by OLUWAMUYIWA** [comment]
Thanks @zshipko !

**Comment by zshipko** [comment]
Closed by #664
