### ISSUE TITLE
discord link in readme is expired

### ISSUE THREAD

**Issue by benthecarman** [extism/extism#669]

**Comment by nilslice** [comment]
will update, thank you! does this one work for you? 

https://extism.org/discord -- or is this redirecting to another expired one for you?

**Comment by nilslice** [comment]
if not, I just generated this one: 

https://discord.gg/nFYWpCAp

sorry about that

**Comment by benthecarman** [comment]
Neither of those work for me
![image](https://github.com/extism/extism/assets/15256660/cc5a2e8f-c9be-4ca3-b3c6-9a8c99350611)

**Comment by bhelx** [comment]
thank you for reporting!

**Comment by benthecarman** [comment]
Got it to work, changed VPN and browser, discord being discord i guess lol
