### ISSUE TITLE
option for a WASM instr limit per call

### ISSUE THREAD

**Issue by walksanatora** [extism/extism#675]
I am trying to look for a wasm runtime (in java) that supports the ability for me to set an execution limit. eg:
execute 100,000 instructions and then return to java currently all the options I have found have been unofficial, broken, or repository removed

**Comment by nilslice** [comment]
this is currently not supported in our Java SDK, but we maintain a pure-Java WebAssembly runtime which might support this in the future. 

If you'd like, please open an issue there to suggest this feature:

https://github.com/dylibso/chicory

**Comment by bhelx** [comment]
Note that chicory does support this now. We decided not to implement this for extism right now because it would be tricky to implement it in a runtime agnostic way that is also performant.
