### ISSUE TITLE
Question about plugin return types

### ISSUE THREAD

**Issue by ur-fault** [extism/extism#677]
While reading the docs, I noticed this sentence in the [Memory ](https://extism.org/docs/concepts/memory) section

> The exact format of the messages is set by the plug-in author.

I don't understand it, wouldn't the host application author set the format? Maybe some json format or something.

Just not sure how it's supposed to work, but thanks in advance.

**Comment by nilslice** [comment]
Yes, you're correct - that's likely just a typo on our side. The host would decide the encoding of the input data, and expect a certain encoding back from the plugin. 

Sorry about that - we'll fix that page!

**Comment by ur-fault** [comment]
Thanks, no prob

**Comment by nilslice** [comment]
I've updated the docs to clarify / fix this. Thank you for pointing it out!
