### ISSUE TITLE
Synchronizing the content of `wasm` folder

### ISSUE THREAD

**Issue by mtb0x1** [extism/extism#681]
Hello,

Can we consider auto-synchronizing the content of wasm folder with  `extism/plugins` ? 
https://github.com/extism/plugins/issues/5 might have an impact on this one.

Thanks.

**Comment by nilslice** [comment]
We can certainly look into it - did you encounter an issue this would solve?

**Comment by mtb0x1** [comment]
When testing https://github.com/extism/extism/issues/673, I faced a small issue :
The `extism/wasm/http.wasm` expose 1 function `http_request`, the one in plugins repo expose 2 functions `http_get` and `http_post`. I was confused for a second by it :D. 

I am not sure if other plugins and other repo that have .wasm copy in them are affected by this. Would be nice to centralize all wasm binaries used in all extism repos in one place.

**Comment by bhelx** [comment]
We've since removed the `plugins` folder and now the tests point directly to the releases on that repo. So i think this should effectively solve the problem. Let me know if i misinterpreted though!
