### ISSUE TITLE
How to unload a plugin?

### ISSUE THREAD

**Issue by furesoft** [extism/extism#703]
I am wondering how could I unload a pülugin and call a special funktion on unloading to cleanup some registrations in my app.

**Comment by nilslice** [comment]
Hey @furesoft, which Host language SDK are you using?

**Comment by mhmd-azeez** [comment]
@furesoft `Plugin` implements `IDisposable` in the .NET SDK, disposing it should release all resources held by the plugin

**Comment by bhelx** [comment]
Let us know if @mhmd-azeez 's answer hasn't unblocked you!
