### ISSUE TITLE
add a feature to control which wasm backend is enabled?

### ISSUE THREAD

**Issue by Kilerd** [extism/extism#706]
currently extism is using cranelift as the backend codegen, but wasmer does support to use LLVM instead. 
can we introduce a new feature into extism to allow user deicide which codegen is used.

P.S. I just wanna compile extism into armv7 target.

**Comment by zshipko** [comment]
Thanks! Right now the Rust runtime only has support for targets supported by Wasmtime - this may change if we develop backends using other runtimes. We have discussed creating Extism bindings for [WAMR](https://github.com/bytecodealliance/wasm-micro-runtime) but haven't made much progress on that yet. Something like that might be the best option for using Extism on armv7.

**Comment by Kilerd** [comment]
hmmm, maybe I dont express my idea correctly.

extism use wasmtime as the WASM runtime provider, and wasmtime includes a cranelift compiler by default to compile the wat text code into wasm bytecode. 
and due to the limitation of cranelift implementation, we cant build extism in some targets like armv7. 
I'm thinking if we can make the function of compiling wat text code into bytecode as opt-in feature( make it optional), then we can make cranelift dependecy as optional?

if I dont wrong, no too many people will use wat text code in production.

**Comment by G4Vi** [comment]
I believe the cranelift compiler is also essential to executing wasm bytecode with wasmtime. According to https://docs.wasmtime.dev/stability-platform-support.html the wasmtime JIT compiler is backed by cranelift and is only for x86_64 and aarch64 at the moment. Also wasmtime doesn't have an interpreter mode.

**Comment by Kilerd** [comment]
okay, it make sense to keep cranelift. my bad though.

let me just close the issue.
