### ISSUE TITLE
getting a list of a plugin’s exported functions

### ISSUE THREAD

**Issue by Somfic** [extism/extism#714]
Hi.

I was wondering if it’d be possible to, given a `Plugin`, figure out which functions are exported by it?

**Comment by nilslice** [comment]
Hey - we don't officially support this via Extism, but you can use another tool we make, Modsurfer. Either statically, via the web[0] or CLI[1], or dynamically in a program using it as an Extism plugin[2].

[0]: https://modsurfer.dylibso.com
[1]: https://github.com/dylibso/modsurfer
[2]: https://modsurfer.dylibso.com/module?hash=0c20c61f67108ebccae1db0be6df7c7d14b2567d5606154278ee390f43e1f408

For [2], via an Extism plugin, you would call the export `parse_module`, passing it the bytes of your wasm plugin, and in return, the plugin will provide a `Module` protobuf. 

We provide Go and Rust libraries, but you can also generate your own protobuf library in any language they support using the `api.proto` as the definition. See the files here: https://github.com/dylibso/modsurfer/tree/main/proto/v1

**Comment by Somfic** [comment]
Awesome thanks for the quick help!

**Comment by nilslice** [comment]
For sure! If you have any issues with these approaches, please let us know. I might also add another export to this plugin (would be a new .wasm) which would just list the exports by name in a JSON list `["count_vowels", "etc"]` so you don't need to deal with the protobuf types... would that help?

**Comment by nilslice** [comment]
@Somfic -- ok, the Extism plugin[0] (new version to download) has an export called `list_extism_funcs`, which just returns the exports that you can call from Extism specifically.

[0]: https://modsurfer.dylibso.com/module?hash=67a67abb2a863ba45967836b9ba75ce9b287c7e5e1a86ff02cfcb27dd41350f4

The usage is like: 

```sh
cat plugin.wasm | extism call modsurfer.wasm list_extism_funcs --stdin | jq 
["export_1", "export_2", ...]
```

**Comment by Somfic** [comment]
Will use the `modsurfer` plugin for now then! :)
