### ISSUE TITLE
Support for Running Java Host Application on Windows

### ISSUE THREAD

**Issue by JiananAlvin** [extism/extism#734]
I am looking to run a Java host application on Windows. Specifically, I want to install the Extism runtime dependency for the Java SDK on a Windows environment. However, I have not been able to find any tutorial or documentation that guides through this process. 

Questions:
1. Does Extism support running Java host applications on Windows, or is it limited to Linux?
2. If it does support Windows, could you provide or point me to a tutorial or documentation on how to install and set up the Extism runtime dependency for Java SDK on Windows?

Thank you for your assistance! :blush:

**Comment by bhelx** [comment]
We don't have a specific tutorial for this combination of targets, but this should work. We have a Java SDK: https://github.com/extism/java-sdk and the README walks through how to setup your dependencies. Have you tried it yet?

You need to use the CLI to install the extism runtime. If you want to skip this step or have trouble, you can download the runtime directly from the releases: https://github.com/extism/extism/releases/tag/v1.4.1 . There are a number of windows builds supported. From there you just need to put it in a place where Java can find it. The Java SDK uses JNA to find the binary, so you just need to put it in a place where JNA will find it, or tell JNA where it is.

**Comment by JiananAlvin** [comment]
Thank you soooooo much for you fast reply.

What I have done:
I found instructions here [Extism Java SDK](https://github.com/extism/java-sdk), but they are for Linux. I manually downloaded the latest release `libextism-x86_64-pc-windows-msvc-v1.4.1.tar.gz`, extracted, and then placed `extism.dll` within `C:\Windows\System32`. However, when I ran my Java host application, I encountered an error related to the `.dll` file at the line `try (var ctx = new Context()) {`:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'extism_context_new': The specified procedure could not be found.

	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:604)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:580)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
	at com.sun.jna.Library$Handler.invoke(Library.java:243)
	at jdk.proxy1/jdk.proxy1.$Proxy0.extism_context_new(Unknown Source)
	at org.extism.sdk.Context.<init>(Context.java:24)
	at example.ExtismExample.main(ExtismExample.java:22)

Process finished with exit code 1
```

Code:
```
package example;

import org.extism.sdk.Context;
import org.extism.sdk.manifest.Manifest;
import org.extism.sdk.wasm.WasmSourceResolver;

import java.nio.file.Path;

public class ExtismExample {

    public static void main(String[] args) {

        var wasmPath = args.length > 0 ? args[0] : "src/main/resources/code.wasm";
        var functionName = args.length > 1 ? args[1] : "count_vowels";
        var input = args.length > 2 ? args[2] : "Hello World";

        var wasmSourceResolver = new WasmSourceResolver();
        var manifest = new Manifest(wasmSourceResolver.resolve(Path.of(wasmPath)));

        System.out.printf("Executing \"%s\" from \"%s\" with input \"%s\"%n", functionName, wasmPath, input);

        try (var ctx = new Context()) {
            try (var plugin = ctx.newPlugin(manifest, false)) {
                var output = plugin.call(functionName, input);
                System.out.println(output);
            }
        }
    }
}
```

**Comment by bhelx** [comment]
Thanks for the code and error message! It sounds like you are on the right path.

This is a pretty common problem across platforms. I'll try to explain why it happens and maybe this will help us figure out a resolution. We don't know where the .dll is on your system. So JNA tries to find it by name: https://github.com/extism/java-sdk/blob/144804285b2a83e10f1c766575e2df4c525685f1/src/main/java/org/extism/sdk/LibExtism.java#L14

JNA has it's own rules and mechanisms for finding this dll and they are different for each platform. So you may need to move it or rename it to something that satisfies JNA. I think JNA maybe has some properties you can set to hint at where to look but you'll need to search JNA docs for that. This document may help https://github.com/java-native-access/jna/blob/master/www/GettingStarted.md

There are some other reasons you may be getting this error. e.g. if the architecture is wrong or something disqualifies the binary. Sometimes, it can unfortunately be kind of hard to tell why Java doesn't want to load a native library.

Let me know if you're still stuck after doing some research.

**Comment by bhelx** [comment]
Took a quick skim through the doc and this is probably the relevant section of things to try:

> Make your target library available to your Java program. There are several ways to do this:
> 
>     The preferred method is to set the jna.library.path system property to the path to your target library. This property is similar to java.library.path, but only applies to libraries loaded by JNA.
>     Change the appropriate library access environment variable before launching the VM. This is PATH on Windows, LD_LIBRARY_PATH on Linux, and DYLD_LIBRARY_PATH on OSX.
>     Make your native library available on your classpath, under the path {OS}-{ARCH}/{LIBRARY}, where {OS}-{ARCH} is JNA's canonical prefix for native libraries (e.g. win32-x86, linux-amd64, or darwin). If the resource is within a jar file it will be automatically extracted when loaded.

**Comment by JiananAlvin** [comment]
Thanks a lot for your advice. 😃 I've made some progress, but the issue persists. Here's an update on what I've done and the current state of the problem:

**Current Setup:**
I placed all four files (`extism.dll`, `extism.dll.lib`, `extism.h`, and `extism.lib`) extracted from `libextism-x86_64-pc-windows-msvc-v1.4.1.tar.gz` in my working directory. I then set the `jna.library.path` to my working directory to ensure JNA can find extism.dll.
![image](https://github.com/extism/extism/assets/80013606/5b45501a-eb80-4cfb-8bfd-e88b31cc8048)


**Observation:**
Without setting the `jna.library.path`, I receive the error "The specified module could not be found."
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'extism':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/extism.dll) not found in resource path (C:\Users\<user name>\Git\extism-java-example-main\target\classes;C:\Users\<user name>\.m2\repository\org\extism\sdk\extism\0.1.0\extism-0.1.0.jar;C:\Users\<user name>\.m2\repository\net\java\dev\jna\jna\5.12.1\jna-5.12.1.jar;C:\Users\<user name>\.m2\repository\com\google\code\gson\gson\2.10\gson-2.10.jar)
```
After setting the `jna.library.path` to my working directory, this error no longer appears, indicating that JNA successfully finds extism.dll. However, I still encounter the error I mentioned previously.

It seems that while JNA can locate the `.dll`, it might be having trouble finding the `extism_context_new` function within the `ddl`?

Thank you for your continued support! 😄

**Comment by JiananAlvin** [comment]
By the way, the code I'm working on can be found here: [Extism Example Code](https://github.com/thomasdarimont/extism-java-example/tree/main).

**Comment by bhelx** [comment]
How did you install the library and where did you get that code from? Context is an older concept that is now gone

**Comment by bhelx** [comment]
Sorry I see you liked. Looks out of date

**Comment by bhelx** [comment]
Your Pom indicates you are using a pre1.0 version of the jdk, you need to upgrade it to version 1. Follow the readme in the Java sdk repo

**Comment by JiananAlvin** [comment]
Thank you so much. It solved. 😊

**Comment by bhelx** [comment]
Excellent! Where did you get that code snippet btw? I want to make sure we don't have some old docs out there.

**Comment by bhelx** [comment]
If you have any other java questions feel free to file on the [Java SDK Issues](https://github.com/extism/java-sdk/issues) we will get back to you quickly. Or join our [discord](https://extism.org/discord) to talk in realtime.

**Comment by JiananAlvin** [comment]
Thank you so much. 😃 You are really kind and helpful! I will join the discord chat for sure. Hope I can somehow contribute to the amazing Extism community some day.

I got the code snippet form one github user's repo [Extism Example Code](https://github.com/thomasdarimont/extism-java-example/blob/main/src/main/java/example/ExtismExample.java).

By the way, I deleted .dll everywhere on my PC. It still works perfectly with dependency in pom without .dll. Does it mean its okay to skip this kind of step on windows?
![image](https://github.com/extism/extism/assets/80013606/a449d103-1ac3-4295-b439-d1afabee6792)

**Comment by bhelx** [comment]
No problem. Happy to help. Thomas is a contributor to the library. @thomasdarimont if you have a moment could you add a note that the repo is out of date and link to the main java-sdk. Or feel free to update it if you have time whatever works :)

**Comment by thomasdarimont** [comment]
Thanks for the heads up! I just updated the example https://github.com/thomasdarimont/extism-java-example/blob/main/src/main/java/example/ExtismExample.java with the latest extism java sdk 1.0.1.
