### ISSUE TITLE
Please add examples of how to interact filesystem and network

### ISSUE THREAD

**Issue by Zane-XY** [extism/extism#787]
While the current greet function example is a good starting point, I believe it would be more beneficial to include practical use cases. For instance, demonstrating how to:
- Read and write files to/from the filesystem
- Send HTTP requests to remote endpoints
would provide users with a better understanding of the plugin's capabilities and potential applications.

**Comment by Zane-XY** [comment]
I did find there're some examples in the repo, for example the try_read and try_write plugin. But when I try to run it either from cli or Rust, I get the same error saying: `Failed to read file: operation not supported on this platform`.

**Comment by bhelx** [comment]
can you provide the CLI command you are using to test? All fs syscalls are disabled by default. You do need to allow specific mapping of guest to host on the command line. The argument for the extism cli is `--alow-path`.

**Comment by zshipko** [comment]
The fs example in `runtime/examples/fs.rs` seems like it should work if you don't use a readonly path - I've just opened a PR to make it more clear what's going on in that example: https://github.com/extism/extism/pull/788
