### ISSUE TITLE
Streaming data?

### ISSUE THREAD

**Issue by anderspitman** [extism/extism#795]
I think the last major wish list item I have for Extism would be support for streaming data. As far as I can tell this isn't currently supported, right?

My project essentially consists of an HTTP handler. HTTP request/response bodies are usually streamed, but currently I have to fully read the body before passing the request to my Extism plugin, and vice versa for the response. This isn't really a problem for my current project, but I have ideas for other wasm projects that could really benefit from streaming.

I still don't know enough about wasm to know if putting plugins in the hot path of an HTTP server would be a good idea. Maybe the overhead from the copies is too high for a fully generalized system like wasm middleware for example.

**Comment by bhelx** [comment]
We do have some plans around supporting this as an extism primitive. I think sometime soon, we'll have support for this in either extism or xtp-bindgen: https://github.com/dylibso/xtp-bindgen. In the mean time, the primitives we have allow you to implement these higher level ideas yourself.

For HTTP there could be two possible designs:

1. Call the export with the minimal HTTPRequest metadata (minus the body). Provide a host function to read the body. This host function can read the whole body or read it in chunks.
2. if you want to stream the data in, where the host has control over when each chunk arrives, you can call an export multiple times that buffers (and or processes) the incoming data in memory and then call some other export when "done".

Both of these would require writing a little bit of wrapper code at the PDK level to hide the details from the user, but are doable.

**Comment by anderspitman** [comment]
Makes sense. Those are both good ideas. Thanks!
